apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dt-py-header-bluegreen
spec:
  host: svc-py-header
  subsets:
  - name: blue
    labels:
      version: blue
  - name: green
    labels:
      version: green
