apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py-http-call
  name: py-http-call
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-http-call
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: py-http-call
    spec:
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-call:1c91e02c69498a6e1ec71c06df884d44864ebe24
        name: py-http-call
        env:
        - name: api_endpoint
          value: "svc-py-header:8080/api/v1"
        - name: BACKGROUND_COLOR
          value: "orange"
        resources: {}
status: {}
