apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py-header
    version: blue
  name: py-header
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-header
      version: blue
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: py-header
        version: blue
    spec:
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-header:7d6dd0e198e1456e152e7403d64294929f3b545a
        name: py-http-echo
        env:
        - name: BACKGROUND_COLOR
          value: "blue"
        resources: {}
status: {}
