apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py-header
    version: blue
  name: py-header
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-header
      version: blue
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: py-header
        version: blue
    spec:
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-header:1b98030d1a76a8543a4c5d4c4b68fc5d9d965015
        name: py-http-echo
        env:
        - name: BACKGROUND_COLOR
          value: "blue"
        resources: {}
status: {}
