apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py-header
    version: green
  name: py-header-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-header
      version: green
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: py-header
        version: green
    spec:
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-header:b35be5629b77b4ea6385e8400b7de2311ddb9339
        name: py-http-echo
        env:
        - name: BACKGROUND_COLOR
          value: "green"
        resources: {}
status: {}

